
#define PANDA_MAJOR_VERSION 1
#define PANDA_MINOR_VERSION 11
#define PANDA_SEQUENCE_VERSION 1
#define PANDA_VERSION 1011000
#define PANDA_NUMERIC_VERSION 1011000
#define PANDA_VERSION_STR "1.11.1"
#define PANDA_ABI_VERSION_STR "1.11"
#define PANDA_DISTRIBUTOR "makepanda"

#undef  PANDA_OFFICIAL_VERSION
